"""Add recurring flags to income sources and budget allocations

Revision ID: 6f3232443873
Revises: 
Create Date: 2025-10-26 22:31:38.275428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3232443873'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring_allocation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurring_allocation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_budget_allocation_recurring', 'recurring_budget_allocation', ['recurring_allocation_id'], ['id'])

    with op.batch_alter_table('income_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring_source', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurring_source_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_income_source_recurring', 'recurring_income_source', ['recurring_source_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_source', schema=None) as batch_op:
        batch_op.drop_constraint('fk_income_source_recurring', type_='foreignkey')
        batch_op.drop_column('recurring_source_id')
        batch_op.drop_column('is_recurring_source')

    with op.batch_alter_table('budget_allocation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_budget_allocation_recurring', type_='foreignkey')
        batch_op.drop_column('recurring_allocation_id')
        batch_op.drop_column('is_recurring_allocation')

    # ### end Alembic commands ###
