"""Add unique constraint to prevent duplicate subcategories

Revision ID: 94aadecb5493
Revises: 6f3232443873
Create Date: 2025-10-28 22:27:17.490461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94aadecb5493'
down_revision = '6f3232443873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_subcategory_name_category', ['name', 'category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subcategory_name_category', type_='unique')

    # ### end Alembic commands ###
